### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '__suppress_context__'

### ISSUE THREAD

**Issue by leonsp** [ViktorStiskala/raven-bash#3]
I'm seeing this error when trying to use `raven-bash` on Alpine Linux with bash:

```
Traceback (most recent call last):
  File "/usr/bin/raven-logger", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/logger/raven_logger.py", line 141, in main
    client.capture(args)
  File "/usr/lib/python3.5/site-packages/logger/raven_logger.py", line 109, in capture
    self._client.capture('raven.events.Exception', data=data, extra=extra)
  File "/usr/lib/python3.5/site-packages/raven/base.py", line 606, in capture
    **kwargs)
  File "/usr/lib/python3.5/site-packages/raven/base.py", line 362, in build_msg
    result = handler.capture(**kwargs)
  File "/usr/lib/python3.5/site-packages/raven/events.py", line 116, in capture
    for exc_info in _chained_exceptions(exc_info):
  File "/usr/lib/python3.5/site-packages/raven/events.py", line 52, in _chained_exceptions
    if exc.__suppress_context__:
AttributeError: 'NoneType' object has no attribute '__suppress_context__'
```

My Python version:

```
# python3 --version
Python 3.5.1
```

**Comment by ViktorStiskala** [comment]
Fixed in v1.0, now supports most recent version of raven-python
